# Generated by Django 5.0.2 on 2025-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guestrental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='mileage_end',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='mileage_start',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_id',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
